Repository desy-ml/cheetah, pull requests merged in 2023-09, with the labels that each got.

#63 Add twiss parameter calculations
  cheetah/particles.py
  setup.py
  test/test_astra_import.py
  test/test_compare_ocelot.py
  test/test_parameter_beam.py
  test/test_particle_beam.py
Labels: enhancement, help wanted

#65 Read Bmad lattice files
  cheetah/__init__.py
  cheetah/accelerator.py
  cheetah/dontbmad.py
  cheetah/particles.py
  cheetah/track_methods.py
  cheetah/utils.py
  docs/dontbmad.rst
  docs/index.rst
  test/ARESlattice.json
  test/bmad/bmad_tutorial_lattice.bmad
  test/test_bmad_conversion.py
  test/test_compare_beam_type.py
  test/test_compare_ocelot.py
  test/test_split.py
Labels: enhancement

#76 Add badges
  .github/workflows/format.yml
  .github/workflows/pytest.yml
  README.md
Labels: documentation, enhancement

#70 11 differentiable cheetah
  .readthedocs.yaml
  README.md
  cheetah/__init__.py
  cheetah/accelerator.py
  cheetah/astralavista.py
  cheetah/dontbmad.py
  cheetah/error.py
  cheetah/latticejson.py
  cheetah/nocelot.py
  cheetah/particles.py
  cheetah/track_methods.py
  cheetah/utils.py
  docs/astralavista.rst
  docs/conf.py
  docs/error.rst
  docs/examples/ARESlatticeStage3v1_9.py
  docs/examples/convert.ipynb
  docs/examples/gradientbased.ipynb
  docs/examples/simple.ipynb
  docs/index.rst
  docs/latticejson.rst
  docs/nocelot.rst
  docs/requirements.txt
  docs/utils.rst
  setup.py
  test/ARESlattice.json
  test/test_bmad_conversion.py
  test/test_equality.py
  test/test_lattice_json.py
  test_bmad.ipynb
  test_torch.ipynb
  tests/__init__.py
  tests/resources/ARESlatticeStage3v1_9.py
  tests/resources/bmad_tutorial_lattice.bmad
  tests/test_astra_import.py
  tests/test_bmad_conversion.py
  tests/test_compare_beam_type.py
  tests/test_compare_ocelot.py
  tests/test_differentiable.py
  tests/test_drift.py
  tests/test_equality.py
  tests/test_lattice_json.py
  tests/test_ocelot_import.py
  tests/test_parameter_beam.py
  tests/test_particle_beam.py
  tests/test_speed.py
  tests/test_split.py
Labels: enhancement

#78 Add newly implemented elements to Ocelot conversion
  cheetah/nocelot.py
  docs/examples/gradientbased.ipynb
  tests/test_compare_ocelot.py
Labels: enhancement

#82 Fix NaN appearing in gradient
  cheetah/track_methods.py
  docs/examples/ARESlatticeStage3v1_9.json
  docs/examples/gradientbased.ipynb
  tests/test_quadrupole.py
Labels: bug

#81 Move converters into separate directory
  cheetah/__init__.py
  cheetah/accelerator.py
  cheetah/converters/__init__.py
  cheetah/converters/astralavista.py
  cheetah/converters/dontbmad.py
  cheetah/converters/nocelot.py
  cheetah/particles.py
  tests/test_compare_ocelot.py
  tests/test_speed.py
Labels: enhancement

#75 Add CHANGELOG.md
  CHANGELOG.md
Labels: documentation, enhancement

#86 Add charge in the Beam classes
  CHANGELOG.md
  cheetah/accelerator.py
  cheetah/converters/astralavista.py
  cheetah/particles.py
  tests/test_astra_import.py
  tests/test_compare_ocelot.py
  tests/test_drift.py
  tests/test_parameter_beam.py
  tests/test_particle_beam.py
  testsomething.ipynb
Labels: enhancement
