Repository desy-ml/cheetah, pull requests merged in 2024-06, with the labels that each got.

#170 Fix dipole tracking issue; Add tests accordingly
  CHANGELOG.md
  cheetah/accelerator/dipole.py
  tests/test_dipole.py
Labels: bug

#172 Fix cavity tracking issue introduced in recent updates
  CHANGELOG.md
  cheetah/accelerator/cavity.py
  tests/test_compare_ocelot.py
Labels: bug

#173 Fix vectorization issue in rbend
  CHANGELOG.md
  cheetah/accelerator/dipole.py
  cheetah/accelerator/rbend.py
  tests/test_compare_ocelot.py
Labels: bug

#185 Fix non-vectorised assignment typo in README
  README.md
Labels: documentation

#188 Add imports to code example in the README
  CHANGELOG.md
  README.md
Labels: enhancement

#142 Add space-charge to Cheetah
  CHANGELOG.md
  cheetah/__init__.py
  cheetah/accelerator/__init__.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/space_charge_kick.py
  cheetah/particles/particle_beam.py
  docs/accelerator.rst
  test.py
  tests/test_space_charge_kick.py
  try_batched.ipynb
Labels: enhancement

#196 Implement Bmad conversion device passing
  .vscode/settings.json
  CHANGELOG.md
  cheetah/accelerator/segment.py
  cheetah/converters/bmad.py
  tests/test_bmad_conversion.py
Labels: bug, enhancement

#201 Drift name
  CHANGELOG.md
  cheetah/accelerator/drift.py
Labels: bug

#202 Update docstring of quadrupole.py
  CHANGELOG.md
  cheetah/accelerator/quadrupole.py
Labels: documentation

#206 Add `dtype` passing to Bmad `Segment` import
  CHANGELOG.md
  cheetah/accelerator/segment.py
  cheetah/converters/bmad.py
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  tests/test_bmad_conversion.py
  tests/test_parameter_beam.py
  tests/test_speed_optimizations.py
Labels: bug
