Repository desy-ml/cheetah, pull requests merged in 2024-05, with the labels that each got.

#151 150 fix cavity tracking
  CHANGELOG.md
  cheetah/accelerator.py
Labels: bug

#146 Add particle generation for 3D uniform ellispoid distribution
  CHANGELOG.md
  cheetah/particles.py
  tests/test_particle_beam.py
Labels: enhancement

#156 Fix ellipsoid spelling error
  cheetah/particles.py
  tests/test_particle_beam.py
Labels: bug

#161 Add Python 3.12 support
  .github/workflows/pytest.yaml
  CHANGELOG.md
Labels: enhancement

#158 Split elements and beams into separate files
  .vscode/ltex.dictionary.en-GB.txt
  CHANGELOG.md
  cheetah/__init__.py
  cheetah/accelerator.py
  cheetah/accelerator/__init__.py
  cheetah/accelerator/aperture.py
  cheetah/accelerator/bpm.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/drift.py
  cheetah/accelerator/element.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/marker.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/rbend.py
  cheetah/accelerator/screen.py
  cheetah/accelerator/segment.py
  cheetah/accelerator/solenoid.py
  cheetah/accelerator/undulator.py
  cheetah/accelerator/vertical_corrector.py
  cheetah/particles/__init__.py
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
  docs/accelerator.rst
  docs/conf.py
  docs/particles.rst
  tests/test_equality.py
  tests/test_lattice_json.py
Labels: enhancement

#166 Update reference from arXiv preprint to PRAB publication
  .vscode/ltex.dictionary.en-GB.txt
  CHANGELOG.md
  CITATION.bib
  README.md
  docs/index.rst
Labels: documentation
