Repository desy-ml/cheetah, pull requests merged in 2024-12, with the labels that each got.

#300 Prevent shadowing of `parameters` method in Beam
  CHANGELOG.md
  cheetah/particles/beam.py
Labels: bug

#291 `ParticleBeam.__getitem__` method
  CHANGELOG.md
  cheetah/particles/particle_beam.py
  tests/test_particle_beam.py
Labels: enhancement

#289 Add `clone` method for beams and elements
  CHANGELOG.md
  cheetah/accelerator/aperture.py
  cheetah/accelerator/bpm.py
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/element.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/rbend.py
  cheetah/accelerator/screen.py
  cheetah/accelerator/segment.py
  cheetah/accelerator/solenoid.py
  cheetah/accelerator/vertical_corrector.py
  cheetah/converters/bmad.py
  cheetah/converters/elegant.py
  cheetah/converters/nxtables.py
  cheetah/converters/ocelot.py
  cheetah/latticejson.py
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
  tests/test_bmad_conversion.py
  tests/test_clone.py
  tests/test_compare_ocelot.py
  tests/test_differentiable.py
  tests/test_dipole.py
  tests/test_elegant_conversion.py
  tests/test_lattice_json.py
  tests/test_plotting.py
Labels: bug, enhancement

#301 Add test for using `nn.Parameter` as element length
  CHANGELOG.md
  tests/test_drift.py
Labels: bug

#303 Fix `nn.Parameter` assignment at initialization
  CHANGELOG.md
  cheetah/accelerator/aperture.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/drift.py
  cheetah/accelerator/element.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/screen.py
  cheetah/accelerator/solenoid.py
  cheetah/accelerator/space_charge_kick.py
  cheetah/accelerator/transverse_deflecting_cavity.py
  cheetah/accelerator/undulator.py
  cheetah/accelerator/vertical_corrector.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
  tests/test_differentiable.py
  tests/test_dipole.py
Labels: bug

#292 Distribution plotting
  CHANGELOG.md
  cheetah/particles/particle_beam.py
  cheetah/utils/__init__.py
  cheetah/utils/plot.py
  tests/test_plotting.py
Labels: enhancement

#308 Fix warnings in test suite
  CHANGELOG.md
  cheetah/accelerator/dipole.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/vertical_corrector.py
Labels: bug
