Repository desy-ml/cheetah, pull requests merged in 2024-10, with the labels that each got.

#208 Enable automatic broadcasting
  .gitignore
  CHANGELOG.md
  cheetah/__init__.py
  cheetah/accelerator/aperture.py
  cheetah/accelerator/bpm.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/drift.py
  cheetah/accelerator/element.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/marker.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/rbend.py
  cheetah/accelerator/screen.py
  cheetah/accelerator/segment.py
  cheetah/accelerator/solenoid.py
  cheetah/accelerator/space_charge_kick.py
  cheetah/accelerator/transverse_deflecting_cavity.py
  cheetah/accelerator/undulator.py
  cheetah/accelerator/vertical_corrector.py
  cheetah/converters/__init__.py
  cheetah/converters/bmad.py
  cheetah/converters/nxtables.py
  cheetah/converters/ocelot.py
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
  cheetah/track_methods.py
  cheetah/utils/__init__.py
  cheetah/utils/bmadx.py
  cheetah/utils/kde.py
  cheetah/utils/physics.py
  tests/test_bpm.py
  tests/test_cavity.py
  tests/test_compare_beam_type.py
  tests/test_compare_ocelot.py
  tests/test_device_dtype.py
  tests/test_differentiable.py
  tests/test_dipole.py
  tests/test_drift.py
  tests/test_kde.py
  tests/test_parameter_beam.py
  tests/test_particle_beam.py
  tests/test_quadrupole.py
  tests/test_reading_nx_tables.py
  tests/test_screen.py
  tests/test_space_charge_kick.py
  tests/test_speed.py
  tests/test_speed_optimizations.py
  tests/test_split.py
  tests/test_tracking_lengthless_elements.py
  tests/test_vectorized.py
Labels: enhancement

#261 Corretly convert hgap in dipole from bmad
  CHANGELOG.md
  cheetah/converters/bmad.py
Labels: bug

#258 Fix lattice pruning for vectorized segments
  CHANGELOG.md
  cheetah/accelerator/segment.py
  tests/test_speed_optimizations.py
Labels: bug

#213 Fix twiss plot
  CHANGELOG.md
  cheetah/accelerator/aperture.py
  cheetah/accelerator/bpm.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/drift.py
  cheetah/accelerator/element.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/marker.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/screen.py
  cheetah/accelerator/segment.py
  cheetah/accelerator/solenoid.py
  cheetah/accelerator/space_charge_kick.py
  cheetah/accelerator/transverse_deflecting_cavity.py
  cheetah/accelerator/undulator.py
  cheetah/accelerator/vertical_corrector.py
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
  cheetah/utils/__init__.py
  cheetah/utils/elementwise_linspace.py
  docs/examples/simple.ipynb
  tests/test_elementwise_linspace.py
  tests/test_plotting.py
Labels: bug

#265 Fix corrector broadcasting bug
  CHANGELOG.md
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/vertical_corrector.py
  tests/test_vectorized.py
Labels: bug

#266 Update documentation for `v0.7` release
  README.md
  cheetah/__init__.py
  cheetah/accelerator/aperture.py
  cheetah/accelerator/bpm.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/drift.py
  cheetah/accelerator/element.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/marker.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/rbend.py
  cheetah/accelerator/screen.py
  cheetah/accelerator/segment.py
  cheetah/accelerator/solenoid.py
  cheetah/accelerator/space_charge_kick.py
  cheetah/accelerator/transverse_deflecting_cavity.py
  cheetah/accelerator/undulator.py
  cheetah/accelerator/vertical_corrector.py
  cheetah/converters/bmad.py
  cheetah/converters/elegant.py
  cheetah/converters/utils/fortran_namelist.py
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
  cheetah/track_methods.py
  docs/accelerator.rst
  docs/converters.rst
  docs/error.rst
  docs/examples/ARESlatticeStage3v1_9.json
  docs/examples/convert.ipynb
  docs/examples/gradientbased.ipynb
  docs/examples/optimize_speed.ipynb
  docs/examples/simple.ipynb
  docs/index.rst
  docs/utils.rst
Labels: documentation

#278 Fix vectorized tracking for `TransverseDeflectingCavity`
  CHANGELOG.md
  cheetah/accelerator/transverse_deflecting_cavity.py
  tests/test_transverse_deflecting_cavity.py
Labels: bug

#281 Fix RPN validation
  CHANGELOG.md
  cheetah/converters/utils/rpn.py
  tests/resources/cavity.lte
  tests/test_rpn.py
Labels: bug
