Repository desy-ml/cheetah, pull requests merged in 2024-11, with the labels that each got.

#284 Improve `Beam` docstrings and type hints
  CHANGELOG.md
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
Labels: documentation

#288 Fix plotting for segments with tensors that require gradients
  CHANGELOG.md
  cheetah/accelerator/segment.py
  tests/test_plotting.py
Labels: bug

#294 Fix wrong argument name in README
  README.md
Labels: documentation

#296 Temporary fix for broken inactive`TransverseDeflectingCavity` in `Segment`
  CHANGELOG.md
  cheetah/accelerator/transverse_deflecting_cavity.py
  tests/test_transverse_deflecting_cavity.py
Labels: bug

#254 Improve default dtype selection
  CHANGELOG.md
  cheetah/accelerator/aperture.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/drift.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/rbend.py
  cheetah/accelerator/screen.py
  cheetah/accelerator/solenoid.py
  cheetah/accelerator/space_charge_kick.py
  cheetah/accelerator/transverse_deflecting_cavity.py
  cheetah/accelerator/undulator.py
  cheetah/accelerator/vertical_corrector.py
  cheetah/converters/nxtables.py
  cheetah/converters/ocelot.py
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
  cheetah/utils/__init__.py
  cheetah/utils/argument_verification.py
  tests/test_compare_beam_type.py
  tests/test_device_dtype.py
  tests/test_elegant_conversion.py
  tests/test_particle_beam.py
  tests/test_screen.py
  tests/test_space_charge_kick.py
  tests/test_vectorized.py
Labels: enhancement

#268 Fix `Aperture` vectorisation issue
  CHANGELOG.md
  cheetah/accelerator/aperture.py
  cheetah/accelerator/bpm.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/drift.py
  cheetah/accelerator/element.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/screen.py
  cheetah/accelerator/space_charge_kick.py
  cheetah/accelerator/transverse_deflecting_cavity.py
  cheetah/particles/beam.py
  cheetah/particles/particle_beam.py
  cheetah/utils/__init__.py
  cheetah/utils/statistics.py
  tests/resources/bmadx/incoming.pt
  tests/test_compare_ocelot.py
  tests/test_dipole.py
  tests/test_drift.py
  tests/test_space_charge_kick.py
  tests/test_statistics.py
  tests/test_transverse_deflecting_cavity.py
  tests/test_vectorized.py
Labels: bug
