Repository desy-ml/cheetah, pull requests merged in 2024-09, with the labels that each got.

#222 Add Elegant Lattice Converter
  CHANGELOG.md
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/segment.py
  cheetah/converters/__init__.py
  cheetah/converters/bmad.py
  cheetah/converters/elegant.py
  cheetah/converters/nxtables.py
  cheetah/converters/ocelot.py
  cheetah/converters/utils/__init__.py
  cheetah/converters/utils/fortran_namelist.py
  docs/converters.rst
  tests/resources/fodo.lte
  tests/test_elegant_conversion.py
Labels: enhancement

#242 Unpin numpy<2.0
  CHANGELOG.md
  setup.py
Labels: enhancement

#249 Fix Bmad collimator length on import
  CHANGELOG.md
  cheetah/converters/bmad.py
  tests/test_bmad_conversion.py
Labels: bug

#252 Fix Cheetah README image display
  CHANGELOG.md
  README.md
Labels: bug, enhancement
