Repository desy-ml/cheetah, pull requests merged in 2025-04, with the labels that each got.

#380 Implement solenoid splitting
  CHANGELOG.md
  cheetah/accelerator/solenoid.py
Labels: enhancement

#372 Bugfix for using screen with GPU
  CHANGELOG.md
  cheetah/accelerator/screen.py
Labels: bug

#405 [WIP] Fix vertical misalignment in screen object
  CHANGELOG.md
  cheetah/accelerator/screen.py
Labels: bug

#394 Fix screen issues associated with negatively charged species
  CHANGELOG.md
  cheetah/accelerator/screen.py
Labels: bug

#398 RPN rework
  CHANGELOG.md
  cheetah/converters/utils/fortran_namelist.py
  cheetah/converters/utils/rpn.py
  tests/resources/bmad_tutorial_lattice.bmad
  tests/resources/fodo.lte
  tests/test_rpn.py
Labels: bug, enhancement

#406 Sextupole implementation
  CHANGELOG.md
  cheetah/__init__.py
  cheetah/accelerator/__init__.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/drift.py
  cheetah/accelerator/element.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/segment.py
  cheetah/accelerator/sextupole.py
  cheetah/track_methods.py
  cheetah/utils/kde.py
  docs/accelerator.rst
  setup.py
  tests/test_clone.py
  tests/test_device_dtype.py
  tests/test_elements.py
  tests/test_sextupole.py
  tests/test_vectorized.py
Labels: enhancement

#417 Fix Bmad parsing LCLS
  CHANGELOG.md
  cheetah/accelerator/segment.py
  cheetah/converters/bmad.py
  cheetah/converters/utils/fortran_namelist.py
  cheetah/converters/utils/rpn.py
  tests/resources/bmad_tutorial_lattice.bmad
Labels: bug

#408 Change `Screen.reading` pixel order to start from bottom left
  CHANGELOG.md
  cheetah/accelerator/screen.py
  cheetah/particles/particle_beam.py
Labels: enhancement

#424 Housekeeping for `v0.7.2` release
  CHANGELOG.md
  docs/conf.py
  setup.py
Labels: release

#409 Fix parsing of kquad and csrcsbend
  CHANGELOG.md
  cheetah/converters/elegant.py
  tests/resources/fodo.lte
Labels: enhancement

#431 `Segment` attribute setting convenience method
  .github/workflows/pytest.yaml
  CHANGELOG.md
  cheetah/accelerator/segment.py
  setup.py
  test_requirements.txt
  tests/resources/bmad/x_tao_#12C+3_Dipole.pt
  tests/resources/bmad/x_tao_#12C+3_Drift.pt
  tests/resources/bmad/x_tao_#12C+3_Quadrupole.pt
  tests/resources/bmad/x_tao_antiproton_Dipole.pt
  tests/resources/bmad/x_tao_antiproton_Drift.pt
  tests/resources/bmad/x_tao_antiproton_Quadrupole.pt
  tests/resources/bmad/x_tao_deuteron_Dipole.pt
  tests/resources/bmad/x_tao_deuteron_Drift.pt
  tests/resources/bmad/x_tao_deuteron_Quadrupole.pt
  tests/resources/bmad/x_tao_electron_Dipole.pt
  tests/resources/bmad/x_tao_electron_Drift.pt
  tests/resources/bmad/x_tao_electron_Quadrupole.pt
  tests/resources/bmad/x_tao_positron_Dipole.pt
  tests/resources/bmad/x_tao_positron_Drift.pt
  tests/resources/bmad/x_tao_positron_Quadrupole.pt
  tests/resources/bmad/x_tao_proton_Dipole.pt
  tests/resources/bmad/x_tao_proton_Drift.pt
  tests/resources/bmad/x_tao_proton_Quadrupole.pt
  tests/test_compare_bmad.py
  tests/test_segment.py
Labels: enhancement
