Repository desy-ml/cheetah, pull requests merged in 2025-07, with the labels that each got.

#480 Add support for elements with negative lengths
  CHANGELOG.md
  cheetah/accelerator/aperture.py
  cheetah/accelerator/bpm.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/custom_transfer_map.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/drift.py
  cheetah/accelerator/element.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/marker.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/screen.py
  cheetah/accelerator/sextupole.py
  cheetah/accelerator/solenoid.py
  cheetah/accelerator/space_charge_kick.py
  cheetah/accelerator/transverse_deflecting_cavity.py
  cheetah/accelerator/undulator.py
  cheetah/accelerator/vertical_corrector.py
  pyproject.toml
  tests/conftest.py
  tests/resources/bmad_tutorial_lattice.bmad
  tests/resources/fodo.lte
  tests/test_bmad_conversion.py
  tests/test_clone.py
  tests/test_device_dtype.py
  tests/test_differentiable.py
  tests/test_drift.py
  tests/test_elegant_conversion.py
  tests/test_elements.py
  tests/test_split.py
  tests/test_vectorized.py
Labels: bug, enhancement

#493 More copy-pasteable README examples
  CHANGELOG.md
  README.md
  docs/examples/convert.ipynb
  docs/examples/simple.ipynb
Labels: documentation

#497 Make warnings available in top-level namespace
  CHANGELOG.md
  cheetah/__init__.py
Labels: enhancement

#501 Adds key-val lookups in context to rpn and infix
  CHANGELOG.md
  cheetah/converters/utils/infix.py
  cheetah/converters/utils/rpn.py
  tests/test_infix.py
  tests/test_rpn.py
Labels: enhancement

#498 Add element property access to the Bmad converter
  CHANGELOG.md
  tests/resources/bmad_tutorial_lattice.bmad
  tests/test_bmad_conversion.py
Labels: bug, enhancement

#496 Make README and simple.ipynb examples the same
  CHANGELOG.md
  README.md
  docs/examples/simple.ipynb
  images/readme_overview_plot.png
Labels: documentation

#511 Upgrade to new release of 3D assets with flipped horizontal corrector and fix credit
  .vscode/ltex.dictionary.en-GB.txt
  CHANGELOG.md
  README.md
  cheetah/utils/cache.py
  docs/index.rst
Labels: bug, documentation

#513 Fix Ocelot-related tests failing
  CHANGELOG.md
  cheetah/particles/beam.py
  test_requirements.txt
  tests/test_compare_ocelot.py
Labels: bug
