Repository desy-ml/cheetah, pull requests merged in 2025-02, with the labels that each got.

#334 Add `pyproject.toml` for compatability with pip 25
  CHANGELOG.md
  pyproject.toml
Labels: bug

#331 Implement converters between `ParameterBeam` and `ParticleBeam`
  CHANGELOG.md
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
  tests/test_parameter_beam.py
  tests/test_particle_beam.py
Labels: enhancement

#338 Add TUHH logo to readme and docs home page
  CHANGELOG.md
  README.md
  docs/index.rst
  images/tuhh.png
Labels: documentation

#344 Reflect required beam argument in readme and documentation
  CHANGELOG.md
  README.md
  docs/examples/simple.ipynb
Labels: documentation

#355 Add link to the new Cheetah Discord server
  CHANGELOG.md
  README.md
  docs/index.rst
Labels: documentation

#340 Automatically detect default `dtype` for lattice and beam importers
  CHANGELOG.md
  cheetah/accelerator/screen.py
  cheetah/accelerator/segment.py
  cheetah/converters/bmad.py
  cheetah/converters/elegant.py
  cheetah/converters/ocelot.py
  cheetah/latticejson.py
  cheetah/particles/beam.py
  cheetah/particles/parameter_beam.py
  cheetah/particles/particle_beam.py
  tests/conftest.py
  tests/test_astra_import.py
  tests/test_bmad_conversion.py
  tests/test_compare_ocelot.py
  tests/test_elegant_conversion.py
  tests/test_lattice_json.py
  tests/test_ocelot_import.py
Labels: enhancement

#350 Make `Segment.subcell` method more flexible
  CHANGELOG.md
  cheetah/accelerator/segment.py
  tests/test_segment.py
Labels: enhancement

#358 Fix typo that said "quadrupole" in a dipole docstring
  CHANGELOG.md
  cheetah/accelerator/dipole.py
Labels: documentation

#357 Fix `is_active` and `is_skippable` of some elements not being boolean properties
  CHANGELOG.md
  cheetah/__init__.py
  cheetah/accelerator/cavity.py
  cheetah/accelerator/dipole.py
  cheetah/accelerator/horizontal_corrector.py
  cheetah/accelerator/quadrupole.py
  cheetah/accelerator/solenoid.py
  cheetah/accelerator/transverse_deflecting_cavity.py
  cheetah/accelerator/vertical_corrector.py
  tests/test_elements.py
Labels: bug
