Repository desy-ml/cheetah, pull requests merged in 2025-08, with the labels that each got.

#527 Create minimal benchmarking setup
  .github/workflows/benchmark.yaml
  .github/workflows/pytest.yaml
  CHANGELOG.md
  test_requirements.txt
  tests/test_benchmark.py
Labels: documentation, enhancement

#286 Add traveling-wave cavity model
  .vscode/ltex.dictionary.en-GB.txt
  CHANGELOG.md
  README.md
  cheetah/accelerator/cavity.py
  cheetah/converters/bmad.py
  cheetah/converters/ocelot.py
  docs/index.rst
  tests/test_compare_ocelot.py
  tests/test_vectorized.py
Labels: enhancement

#531 Fix typo saying Bmad in Elegant import method docstring
  CHANGELOG.md
  cheetah/accelerator/segment.py
  cheetah/converters/elegant.py
Labels: bug, documentation

#534 Methods for getting the element names / indices for segment
  CHANGELOG.md
  cheetah/accelerator/segment.py
  tests/test_segment.py
Labels: enhancement
