Repository desy-ml/cheetah, pull requests merged in 2025-06, with the labels that each got.

#455 Fix import of `CustomTransferMap`
  CHANGELOG.md
  cheetah/converters/elegant.py
  tests/test_elegant_conversion.py
Labels: bug

#411 Regex tweaks and test
  CHANGELOG.md
  cheetah/accelerator/segment.py
  cheetah/converters/utils/fortran_namelist.py
  tests/resources/fodo.lte
  tests/test_elegant_conversion.py
Labels: enhancement

#461 Fix minimum version of PyTorch compatible with Cheetah
  CHANGELOG.md
  setup.py
Labels: bug

#465 Fix and test device issue with `randomly_subsampled`
  CHANGELOG.md
  cheetah/particles/particle_beam.py
  tests/test_particle_beam.py
Labels: bug

#469 Increase the precision of base_rmatrix calculation to double precision
  CHANGELOG.md
  cheetah/track_methods.py
  tests/test_quadrupole.py
Labels: bug

#471 Improve the cov calculation in ParticleBeam to alllow batched calculation
  CHANGELOG.md
  cheetah/particles/particle_beam.py
  cheetah/utils/__init__.py
  cheetah/utils/statistics.py
  tests/test_compare_beam_type.py
  tests/test_dipole.py
  tests/test_drift.py
  tests/test_parameter_beam.py
  tests/test_particle_beam.py
  tests/test_quadrupole.py
  tests/test_space_charge_kick.py
  tests/test_speed.py
  tests/test_statistics.py
  tests/test_transverse_deflecting_cavity.py
Labels: bug

#458 Infix parser
  CHANGELOG.md
  cheetah/converters/utils/fortran_namelist.py
  cheetah/converters/utils/infix.py
  tests/test_infix.py
Labels: enhancement

#474 Improve numerical precision of inactive elements
  CHANGELOG.md
  cheetah/track_methods.py
  tests/test_quadrupole.py
Labels: bug, enhancement
